# Generated by Django 5.1.2 on 2024-10-27 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("announcements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Сумма к оплате"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "goods",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="announcements.announcement",
                        verbose_name="Товары",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Корзина",),
                "verbose_name_plural": ("Корзины",),
                "ordering": ("id",),
            },
        ),
    ]
