# Generated by Django 5.1.2 on 2024-10-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
            },
        ),
        migrations.AlterField(
            model_name="announcement",
            name="price",
            field=models.PositiveIntegerField(verbose_name="Цена товара"),
        ),
    ]
