# Generated by Django 5.1.2 on 2024-11-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_goods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("unpaid", "Не оплачен"), ("paid", "Оплачен")],
                default="unpaid",
                max_length=100,
                verbose_name="Статус заказа",
            ),
        ),
    ]
